apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: nginx
manifests:
 rawYaml:
 - ./k8s/1_namespace.yaml
 - ./k8s/2_deployment.yaml
 - ./k8s/3_service.yaml

deploy:
  kubectl: {}
  statusCheck: true
  statusCheckDeadlineSeconds: 2400 # High timeout required with autopilot as scaling can be slow