apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: app-a
spec:
  selector:
    matchLabels:
      app: app-a
  replicas: 1 
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: europe-west4-docker.pkg.dev/gateway-demos/demos/app:latest
        ports:
        - containerPort: 8080
        env:
          - name: VERSION
            value: "Version 0"
          - name: COLOUR
            value: "blue"
          - name: TEAM
            value: "Team A"