apiVersion: v1
kind: Namespace
metadata:
  name: single-cluster-gateway
  labels:
    single-cluster-gateway: "true"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: single-cluster-gateway
spec:
  parentRefs:
  - name: external-http-single-cluster
    namespace: single-cluster-gateway
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301